# Generated by Django 2.0.1 on 2018-01-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='activé')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='dernière synchronisation')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
                ('remote_url', models.CharField(max_length=2500, verbose_name='url du dépot')),
            ],
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='ssh_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.SSHKey'),
        ),
        migrations.AddField(
            model_name='mirror',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirrors_as_destination', to='api.Repository', verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='mirror',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirrors_as_origin', to='api.Repository', verbose_name='origine'),
        ),
        migrations.AddField(
            model_name='mirror',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='propriétaire'),
        ),
    ]
