# Generated by Django 2.0.1 on 2018-01-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirror',
            name='destination',
            field=models.CharField(max_length=250, verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='mirror',
            name='origin',
            field=models.CharField(max_length=250, verbose_name='origine'),
        ),
    ]
