# Generated by Django 2.0.1 on 2018-01-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='ssh_key',
        ),
        migrations.AddField(
            model_name='mirror',
            name='ssh_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.SSHKey'),
        ),
        migrations.AlterField(
            model_name='sshkey',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sshkey',
            name='public_key',
            field=models.TextField(blank=True),
        ),
    ]
