# Generated by Django 2.0.1 on 2018-01-28 16:52

from django.db import migrations, models
import gitsyncer.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180128_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirror',
            name='token',
            field=models.CharField(default=gitsyncer.api.models.random_token, max_length=250, unique=True, verbose_name='clef'),
        ),
    ]
