version: '3'

services:

  rabbitmq:
    image: rabbitmq:alpine
    networks:
      - celery
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database
  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
      BROKER_URL: amqp://guest@rabbitmq/
    volumes:
      - clones:/app/clones
    ports:
      - "8001:8000"
    networks:
      - database
      - celery
    depends_on:
      - db
      - rabbitmq
  celery-scheduler:
    build: .
    command: celery -A gitsyncer beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
      BROKER_URL: amqp://guest@rabbitmq/
    volumes:
      - clones:/app/clones
    networks:
      - database
      - celery
    depends_on:
      - db
      - rabbitmq
  celery-worker:
    build: .
    command: celery -A gitsyncer worker -l info
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
      BROKER_URL: amqp://guest@rabbitmq/
    volumes:
      - clones:/app/clones
    networks:
      - database
      - celery
    depends_on:
      - db
      - rabbitmq

networks:
  database:
  celery:

volumes:
  clones:
  db-data: